name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install java
        run: |
          sudo apt-get update
          sudo apt install openjdk-17-jdk openjdk-17-jre
